"use client";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../component/Header";
import Footer from "../component/Footer";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css"; // Import AOS styles

// export const metadata = {
//   title: "Frisky Panda",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, Component, pageProps }) {
  useEffect(() => {
    AOS.init({
      duration: 1000, // Animation duration (in milliseconds)
      easing: "ease-in-out", // Easing option for animations
      once: false, // Whether animation should happen only once
    });
  }, []);
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
